### ISSUE TITLE
Plugin does not work with WebStorm 11

### ISSUE THREAD

**Issue by onchainguy-btc** [luonanqin/intellij-idea-plugins#1]
Hi, brilliant idea for a plugin. Just tested it with WebStorm 11. Unfortunately it doesn't seem to work there. The plugin is installed but neither the default shortcut works nor does the plugin appear in the Keymap configuration. Would be great if you have an idea? Otherwise I would take a look at it and make a pull request. Unfortunately I am a noobie in developing IntelliJ plugins.

Cheers!

**Comment by xinshangshangxin** [comment]
I also found it not work in webstorm 11, when can fix it?

**Comment by yangnuowei88** [comment]
yes ,when can fix it!

**Comment by luonanqin** [comment]
Sorry for my late reply cause I was so busy for the past six months. Anyway ,I'll solve the problem as soon as possilble if I am free after work .

**Comment by gherkins** [comment]
+1
would be much appreciated  :)

**Comment by luonanqin** [comment]
New version 1.1.0 has publish.You can update from "https://plugins.jetbrains.com/plugin/7606?pr=idea" @seb0zz @xinshangshangxin @yangnuowei88 @gherkins

**Comment by gherkins** [comment]
great - works like a charme in phpstorm 10.0.3 :+1:

**Comment by xinshangshangxin** [comment]
**it works for me; thanks!** :+1:

**Comment by onchainguy-btc** [comment]
Awesome :heart_eyes:
