### ISSUE TITLE
Extend support for 2020.* versions of ide

### ISSUE THREAD

**Issue by ChrisGalliano** [luonanqin/intellij-idea-plugins#14]
The current version of the "Scroll From Source" cannot be installed through the marketplace in new versions of ide.
![2020-11-01_17-29](https://user-images.githubusercontent.com/17964229/97807163-ee4a7b80-1c67-11eb-9429-0b814cecec32.png)

**Comment by ChrisGalliano** [comment]
Is it possible to extend support for 2020.*?

**Comment by vepr85** [comment]
only by creating PR with fix

**Comment by hanqiankun** [comment]
![image](https://user-images.githubusercontent.com/44518383/101352669-79eda280-38cd-11eb-810b-3399be2c2d5b.png)
it works~
